<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <RootNamespace>LidDock.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <GarbageCollectionAdaptationMode>0</GarbageCollectionAdaptationMode>
    <EventSourceSupport>false</EventSourceSupport>
    <StackTraceSupport>false</StackTraceSupport>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
    <StartupHookSupport>false</StartupHookSupport>
    <TieredCompilation>false</TieredCompilation>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\LidDock.png" />
    <Resource Include="Assets\LidDock.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LidDock.Core\LidDock.Core.csproj" />
    <ProjectReference Include="..\LidDock.Windows\LidDock.Windows.csproj" />
    <ProjectReference Include="..\LidDock.Diagnostics\LidDock.Diagnostics.csproj" />
  </ItemGroup>

</Project>
